platform :ios, '8.0'
target 'consigliere' do
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
pod 'GoogleMaps'
pod 'GooglePlacePicker'
pod 'GooglePlaces'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNBackgroundFetch', :path => '../node_modules/react-native-background-fetch'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'yoga'
            target.build_configurations.each do |config|
                config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
                config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
            end
        end
    end
end
